### ISSUE TITLE
.container css class

### ISSUE THREAD

**Issue by orochies** [biig-io/ngx-tabset#2]
Hi, excellent work but, I could remove the container class, I have a global css that interferes with the design due to the container class, and I see it does not do much. regards...

**Comment by maximelafarie** [comment]
Hi, thank you @orochies ! 😄 
I will fix it right now, how about the possibility to set custom class names instead of the `.container` class ?
I will let you know when it's released ! 😉

**Comment by maximelafarie** [comment]
@orochies New fixed version's now released! 😄 

Now, the `.container` classes disappears and you now have the possibility to add your own custom class. You can check it out in the updated doc here : https://github.com/biig-io/ngx-tabset#style-and-customization-options

Thank you for your issue and feel free to make other feedbacks! 👍
