### ISSUE TITLE
demo url gives 404

### ISSUE THREAD

**Issue by manjeet13** [biig-io/ngx-tabset#30]
the url for demo https://biig-io.github.io/ngx-tabset/ doesn't work and gives 404

**Comment by maximelafarie** [comment]
Hi @manjeet13. Yes I saw that few days ago, I'm working on a new release that will fix some bugs and make the demo work again! Thank you for reporting it!

**Comment by manjeet13** [comment]
no problem, cheers!

**Comment by maximelafarie** [comment]
It's ok since PR #31 has been merged. Thank you again for your report! 
Cheers! 🖖
